picameraapp/core/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth.views import LoginView



app_name = 'core'

urlpatterns = [
	path('',LoginView.as_view(),name='login'),
	path('add_plant/',views.Create_Plant.as_view(),name='add_plant'),
	path('loggedin/',views.LoggedIn.as_view(),name='loggedin'),
	path('upload_photo/<int:pk>/',views.UploadPhoto.as_view(),name='upload_photo'),
	path('<int:pk>/delete/', views.Delete_Plant_View.as_view(), name='delete_plant'),
    path('download/images/<str:pk>/',views.download_image,name='download_image'),
]

picameraapp/picameraapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('core.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

picameraapp/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
import string, random, piexif, os
from uuid import uuid4
from django.conf import settings
from PIL import Image

# Create your models here.
def path_and_rename(instance, filename):
    #room_code = instance.beerroom.room_code
    pk = instance.user_id
    upload_to = 'images/{id}'.format(id=pk)
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)

class Plant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    description = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    total_pictures = models.IntegerField()
    active_pi = models.BooleanField()



class Photos(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(Plant, on_delete=models.CASCADE)
    photo_room_image = models.ImageField(upload_to=path_and_rename, validators=[FileExtensionValidator(allowed_extensions=['png','jpeg','jpg'])])


    def __str__(self):
        return self.id + self.user

    def save(self, *args, **kwargs):
        super(Photos, self).save(*args, **kwargs)
        #img = Image.open(self.photo_room_image.path)
        img = Image.open(self.photo_room_image.path)
        if "exif" in img.info:
            exif_dict = piexif.load(img.info["exif"])

            if piexif.ImageIFD.Orientation in exif_dict["0th"]:
                orientation = exif_dict["0th"].pop(piexif.ImageIFD.Orientation)
                exif_bytes = piexif.dump(exif_dict)

                if orientation == 2:
                    img = img.transpose(Image.FLIP_LEFT_RIGHT)
                elif orientation == 3:
                    img = img.rotate(180)
                elif orientation == 4:
                    img = img.rotate(180).transpose(Image.FLIP_LEFT_RIGHT)
                elif orientation == 5:
                    img = img.rotate(-90, expand=True).transpose(Image.FLIP_LEFT_RIGHT)
                elif orientation == 6:
                    img = img.rotate(-90, expand=True)
                elif orientation == 7:
                    img = img.rotate(90, expand=True).transpose(Image.FLIP_LEFT_RIGHT)
                elif orientation == 8:
                    img = img.rotate(90, expand=True)

                img.save(self.photo_room_image.path, exif=exif_bytes)
        if img.height > 1942 or img.width > 2590:
            output_size = (1940,2588)
            img.thumbnail(output_size)
            img.save(self.photo_room_image.path)

picameraapp/core/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Plant, Photos



class AddPlantForm(forms.ModelForm):
	name = forms.CharField(required=True)
	name.widget.attrs['class'] = 'form-control'
	name.widget.attrs['placeholder'] = 'Chili, Tomato etc.'

	description = forms.CharField(required=True)
	description.widget.attrs['class'] = 'form-control'
	description.widget.attrs['placeholder'] = 'Description of the plant you are waiting to grow'

	active_pi = forms.BooleanField(required=False)
	active_pi.widget.attrs['class'] = 'form-control-checkbox'
	class Meta:
		model = Plant
		fields = ['name','description', 'active_pi']

class UploadPhotoForm(forms.ModelForm):
    class Meta:
        model = Photos
        fields = ['photo_room_image']

picameraapp/core/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth import views

from django.views.generic import (CreateView, 
                                    UpdateView, 
                                    DeleteView, 
                                    DetailView, 
                                    TemplateView, 
                                    ListView, 
                                    View, 
                                    FormView)
from time import sleep
from django.contrib.auth.models import User
from .models import Photos, Plant
from .forms import AddPlantForm, UploadPhotoForm
from django.db.models import (Avg, 
                            Count, 
                            Min, 
                            Sum)
from django.contrib.auth.mixins import LoginRequiredMixin
#import RPi.GPIO as GPIO
import time, os
from datetime import datetime
import tempfile, zipfile
from django.conf import settings
from wsgiref.util import FileWrapper
from django.http import HttpResponse
from django.http import HttpResponseRedirect

import picamera
MEDIA_ROOT = settings.MEDIA_ROOT

# Create your views her
class LoggedIn(LoginRequiredMixin,TemplateView):
    template_name = 'login_index.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(
            *args, **kwargs)
        user_id = self.request.user.id
        get_plants = Plant.objects.filter(user_id=user_id).order_by('-created_at')
        get_total_plants = (Plant.objects
            .filter(user_id=user_id)
            .aggregate(the_sum=Sum('total_pictures')))    
        ctx['get_plants'] = get_plants
        ctx['get_total_plants'] = get_total_plants
        return ctx

class Create_Plant(LoginRequiredMixin, CreateView):
	model = Plant
	form_class = AddPlantForm
	template_name = 'create_plant.html'

	def form_valid(self, form):
		form.instance.user_id = self.request.user.id
		form.instance.total_pictures = 0
		form = form.save()
		return super().form_valid(form)

	def get_success_url(self):
		return reverse('core:loggedin')

class UploadPhoto(LoginRequiredMixin,CreateView):
    model = Photos
    form_class = UploadPhotoForm
    template_name = 'upload_photo.html'


    def form_valid(self, form):
        date_now = datetime.now()
        files = self.request.FILES.getlist('photo_room_image')
        borje = self.kwargs['pk']
        if files:
            user_id = self.request.user.id
            pk = self.kwargs['pk']
            plant_info = Plant.objects.get(id=pk)
            form.instance.user_id = pk
            plant_info.total_pictures = plant_info.total_pictures + 1
            plant_info.save()
            form = form.save(commit=False)
            form.save()
            #GPIO.setmode(GPIO.BCM)
            #GPIO.setwarnings(False)
            #GPIO.setup(18,GPIO.OUT)
            #GPIO.output(18,GPIO.HIGH)
            #time.sleep(2)
            #GPIO.output(18,GPIO.LOW)
            return super().form_valid(form)
        else:
            form = UploadPhotoForm()

    def get_success_url(self):
        return reverse('core:loggedin')


class Delete_Plant_View(DeleteView):
    template_name = 'delete_plant.html'
    model = Plant

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(
            *args, **kwargs)
        return ctx
    def get_success_url(self):
        return reverse('core:loggedin')



def download_image(request, pk):
        """                                                                         
        Create a ZIP file on disk and transmit it in chunks of 8KB,                 
        without loading the whole file into memory. A similar approach can          
        be used for large dynamic PDF files.                                        
        """
        product_image = Photos.objects.filter(user_id__id=pk).values_list('photo_room_image', flat=True)
        temp = tempfile.TemporaryFile()
        archive = zipfile.ZipFile(temp, 'w', zipfile.ZIP_DEFLATED)
        i = 0
        for index in product_image:
            filename = settings.MEDIA_ROOT + "/" +index # Replace by your files here.  
            archive.write(filename, 'file{name}'.format(name=index)) # 'file%d.png' will be the
        archive.close()
        temp.seek(0)
        wrapper = FileWrapper(temp)
        response = HttpResponse(wrapper, content_type='application/zip')
        response['Content-Disposition'] = 'attachment; filename=photos.zip'
        return response

picameraapp/core/templates/base.html
{% load static %}
{% load tz %}
{% timezone "Europe/Stockholm" %}
<html>
<head>
    <title>{% block title %} Growth | Login {% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}">
    
    <!--Custom styles-->
</head>
<div class="content-wrapper">
        {% block content %}
        if you se this something is wrong
        {% endblock content %}
    </div>
{% endtimezone %}

picameraapp/core/templates/base_admin.html
{% load static %}
{% load tz %}
{% timezone "Europe/Stockholm" %}
<html>

<head>
    <title>{% block title %} Dashboard | Growth {% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/base.css' %}">
    <style type="text/css" media="screen">
    @font-face {
        font-family: 'AbrilFatface';
        src: local('AbrilFatface'),
        url('{% static 'fonts/IndieFlower-Regular.ttf' %}');
    }
    </style>
    <!--Custom styles-->
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <a class="navbar-brand" href="#">Growth</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:loggedin' %}"><i class="fas fa-home"></i> Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:add_plant' %}"><i class="fab fa-pagelines"></i> Add Plant</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper">
    {% block content %}
    if you se this something is wrong
    {% endblock content %}
</div>
{% endtimezone %}

picameraapp/core/templates/create_plant.html
{% extends 'base_admin.html' %}
{% block title %}Growth - Add Plant{% endblock title %}
{% block content %}
<div class="container">
    <div class="container" style="text-align: center;">
        <h1>Add a plant</h1>
        <i class="fas fa-leaf fa-9x"></i>
    </div>
    <div class="container">
        <form class="" method="post">
            <div class="form-group">
                {% csrf_token %}
                <label for="email">Name:</label>
                {{form.name}}
            </div>
            <div class="form-group">
                <label for="email">Description:</label>
                {{form.description}}
            </div>
            <div class="form-group">
                <label for="email">Raspberry Pi Camera</label>
                {{form.active_pi}}
            </div>
            <div class="form-group">
                <div class="col-sm">
                    <input type="submit" name="" value="Create" class="btn btn-primary float-right">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

picameraapp/core/templates/delete_plant.html
{% extends 'base_admin.html' %}
{% block title %}Growth - Delete Plant{% endblock title %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="container py-5">
    <form class="" action="." method="post">
        <h1>Confirm Delete</h1>
        {%csrf_token%}
        <div class="form-actions">
            <input type="submit" name="" value="Delete" class="btn btn-primary">
            <a href="{% url 'core:loggedin' %}" class="btn btn-info">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

picameraapp/core/templates/login_index.html
{% extends 'base_admin.html' %}
{% block title %}Growth - Login{% endblock title %}
{% block content %}
<style type="text/css" media="screen">

</style>
<div class="row">
    <div class="col-lg">
        <div class="card">
            <h3>Total Pictures: <b>{{get_total_plants.the_sum}}</b></h3>
            <div class="container">
                <h4><b>John Doe</b></h4>
                <p>Architect & Engineer</p>
            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="card">
            <h3>Total Days Documented: </h3>
            <div class="container">
                <h4><b>John Doe</b></h4>
                <p>Architect & Engineer</p>
            </div>
        </div>
    </div>
</div>
<div style="overflow-x:auto; margin:auto; text-align: auto;">
    <table style="text-align: auto;">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Created</th>
            <th>Total Photos</th>
            <th>Download Photos</th>
            <th>Delete Photos</th>
        </tr>
        {% for plant in get_plants %}
        <tr>
            <td>{{plant.name}}</td>
            <td>{{plant.description}}</td>
            <td>{{plant.created_at}}</td>
            <td>{{plant.total_pictures}}</td>
            <td><a href="{% url 'core:upload_photo' plant.id %}">Uppload Photo</a></td>
            <td><a href="{% url 'core:download_image' plant.id %}">Download Photos</a></td>
            <td><a href="{% url 'core:delete_plant' plant.id %}">Delete Plant</a></td>
            
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

picameraapp/core/templates/upload_photo.html
{% extends 'base_admin.html' %}
{% block title %}Growth - Upload Photo{% endblock title %}
{% block content %}
    <div class="row">
    <div class="col" style="margin: 2%;">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}{{ field.label}}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}{{form.field.label}}</strong>
            </div>
            {% endfor %}
            {% endif %}
            {% csrf_token %}
            <p>Ladda upp en bild</p>
            {{form.photo_room_image}}
            <div class="col" style="margin-top: 5%;">
            <button type="submit" class="btn btn-primary float-right">Upload</button></div>
        </form>
    </div>
    </div>
{% endblock content %}